#ifndef idt
#define idt
//implemented
void TIMER_INTERRUPT();
void IDT_DF();

void FL();
void Int0x80Handler();
void PS2_HANDLER();
void PS2_HANDLER12();
void SPIRQ();
void SER04();
//autogenerated
void IDT_DE();
void IDT_DB();
void IDT_NMI();
void IDT_BP();
void IDT_OF();
void IDT_BR();
void IDT_UD();
void IDT_NM();
void IDT_TS();
void IDT_NP();
void IDT_SS();
void IDT_GP();
void IDT_PF();
void IDT_MF();
void IDT_AC();
void IDT_MC();
void IDT_XM();
void IDT_VE();
void IDT_CP();
#endif
